repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
    -   id: format
        name: format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
    -   id: typecheck
        name: typecheck
        entry: make typecheck
        language: system
        types: [python]
        pass_filenames: false
    -   id: security
        name: security
        entry: make security
        language: system
        types: [python]
        pass_filenames: false
    -   id: test
        name: test
        entry: make test
        language: system
        types: [python]
        pass_filenames: false
